
server:
  port: 80

# DataBase Settings : hikariCP : https://github.com/brettwooldridge/HikariCP
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fattle?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: ssafy
      password: ssafy
      pool-name: Hikari Connection Pool
      # hikariCP property setting
      maximum-pool-size: 50
      minimum-idle: 50
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
  # File Upload size Setting
#  servlet:
#    multipart:
#      max-file-size: 25MB
#      max-request-size: 25MB
  # swagger setting >> Failed to start bean 'documentationPluginsBootstrapper'; error
  mvc:
    pathmatch:
      matching-strategy=ANT_PATH_MATCHER

# File upload path : window
#file:
#  path:
#    nodeValue: C:/board/upload/
#    upload-images: C:/board/upload/imageUpload
#    upload-files: C:/board/upload/fileUpload/

# log level Setting
logging:
  level:
    root: info
    com:
      fattle: debug
    zaxxer:
      hikari:
        pool:
          HikariPool: debug

oauth:
  kakao:
    client-id: 40a6ee1bb9a630be39ffadabd71c51bd
    url:
      auth: https://kauth.kakao.com/oauth/authorize
      api: https://kapi.kakao.com

# kakao login
rest-api-key: 40a6ee1bb9a630be39ffadabd71c51bd
redirect-uri: http://localhost:8080/login-callback
client-secret: 0YLbQqhu3njB5LYDJdNpYw23p8I6XN3E
authorize-uri: https://kauth.kakao.com/oauth/authorize
token-uri: https://kauth.kakao.com/oauth/token
kakao-api-host: https://kapi.kakao.com

