
server:
  port: 8000


spring:
  profiles:
    include: oauth
  # DataBase Settings : hikariCP : https://github.com/brettwooldridge/HikariCP
  datasource:
    url: jdbc:mysql://localhost:3306/fattle?serverTimezone=Asia/Seoul&useUniCode=yes&characterEncoding=UTF-8
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: fattle
      password: fattle
      pool-name: Hikari Connection Pool
      # hikariCP property setting
      maximum-pool-size: 50
      minimum-idle: 50
      connection-timeout: 5000
      connection-init-sql: SELECT 1
      idle-timeout: 600000
      max-lifetime: 1800000
      auto-commit: true
#  # File Upload size Setting
##  servlet:
##    multipart:
##      max-file-size: 25MB
##      max-request-size: 25MB
#  # swagger setting >> Failed to start bean 'documentationPluginsBootstrapper'; error
#  mvc:
#    pathmatch:
#      matching-strategy=ANT_PATH_MATCHER

# File upload path : window
#file:
#  path:
#    nodeValue: C:/board/upload/
#    upload-images: C:/board/upload/imageUpload
#    upload-files: C:/board/upload/fileUpload/


## Swagger setting
springdoc:
  packages-to-scan: com.sixman.fattle.api.controller
  swagger-ui:
    path: /api-docs
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: alpha
    disabled-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  show-actuator: true
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8


# log level Setting
logging:
  level:
    root: info
    org:
      springframework:
        root: debug
        web: debug
    com:
      fattle: debug
    zaxxer:
      hikari:
        pool:
          HikariPool: debug


# OpenVidu Setting
openvidu:
  public-ip: https://13.209.80.143
  secret: fattle